### ISSUE TITLE
Prevention of NaN value appearance by torch.log value

### ISSUE THREAD

**Issue by sdw0316** [kupl/synthrl#10]
where to give eps=1e-7 value?

**Comment by henrylee97** [comment]
The NaN value was from wrong computation of following:
```
loss +=  - (y_value.float().log()).reshape(1)
```
and so necessarily nearly zero values were applied on `.log()` function.

Now Resolved as
```
loss +=  ( (1 -  y_value.float()) + eps ).log().reshape(1)
```
