### ISSUE TITLE
Add a list Language

### ISSUE THREAD

**Issue by sooyoungcha** [kupl/synthrl#3]
1. 현재까지 ("scanl1"함수를 제외하고는) DeepCoder에서 등장한 DSL 내용은 모두 반영하였음.
- IF, LOOP같은 control flow문의 추가 반영이 필요함

---------

2. `func`의 문법 중
```
	| "APPEND" VAR VAR	-> append
	| "CONS" VAR		-> cons
	| "INIT_BLANK"		->init_blank
```
는 본 연구에서 추가적으로 생성된 function 기능인데, 추가 구현이 요구된다.

**Comment by henrylee97** [comment]
Decided not to implemented.
