### ISSUE TITLE
Problem of imbalance data samples when Training (policy/value) Neural Net via Self-play

### ISSUE THREAD

**Issue by sooyoungcha** [kupl/synthrl#4]
`SynthRL` will follow Alpha(Go) Zero pipeline, and thus will involve massive amount of self-playing task. The results of self-playing will be used as dataset for training the neural net $f_\theta(s)=(p,v)$.

In Go and other board games such as Chess, Shogi, there will be no special problem having self-play results as good quality dataset.

However, in Program Synthesis, the situation should be reconsidered: most of time of self-play(synthesis) time should have negative(i.e, failed to synthesis) data sample and only few cases may produce positive(i.e succeeded to synthesis) data sample. (It will be the same case for Verifier either).

This situation somehow reminds me of data _imbalace problem_ mostly appeared in the Supervised Classification problem, and of course, I don't have clue if the same dataset imbalance problem may appear in RL, especially in AlpahGo Zero pipeline problem.

If it is so, we may consider using some special data augmentation technique somehow....

**Comment by henrylee97** [comment]
Training $f_\theta$ it self is actually a Supervised Learning, and therefore should have problem of imbalance data.

**Comment by henrylee97** [comment]
Problem relieved as an episode gets longer.
