### ISSUE TITLE
Some issues left for bit-vector language

### ISSUE THREAD

**Issue by sooyoungcha** [kupl/synthrl#6]
- Implement class `BOOLNode`: Soon will do.
- Implement `pretty_print()`: Will do, but shall discuss on how to print it.
- Implement class `ConstNode`: Must discuss, regarding on our target benchmarks.
- It is unclear which case our target language concerns: signed or unsigned?

**Comment by henrylee97** [comment]
- `ConstNode` follows the benchmarks in `Euphony`
- We decided to consider signed cases.

**Comment by henrylee97** [comment]
All implemented.
