### ISSUE TITLE
Range of output of value function

### ISSUE THREAD

**Issue by sooyoungcha** [kupl/synthrl#8]
The output of value function is expected as a value in between (-inf, +eta), where eta > 1.
However, traditional activation functions like tanh returns a value in betwen (-1, +1).

We need a special function that can make a value bounded in (-inf, +eta).

**Comment by henrylee97** [comment]
ELU(Exponential Linear Unit) gives a value in between (-1, +inf).
Therefore, -eta * ELU(x) gives a value in between (-inf, +eta).

**Comment by henrylee97** [comment]
Softplus function gives a value in between (0, +inf).
Therefore, -Softplus(x) + eta gives a value in between (-inf, +eta).
